### ISSUE TITLE
Issue with SMTP via javaxmail api

### ISSUE THREAD

**Issue by philiplourandos** [greenmail-mail-test/greenmail#89]
Hi there,

I have an application using spring-integration to poll a mail server and store the messages in the designated inbox.

I am able to start the green mail server and send a mail. However the javaxmail api is where thing go wrong. In com.sun.mail.imap.protocol.IMAPProtocol#processGreeting a check is made to see if the IMAP response key is equal to 'PREAUTH' which it is not, the message just contains: '220 /127.0.0.1 GreenMail SMTP Service Ready at port 3025'. 

I am perhaps not using javaxmail properties that would forgo this preauth step? Any help would be appreciated.

**Comment by marcelmay** [comment]
Can you provide a simple test case or at least the relevant Spring configuration you're using?

**Comment by philiplourandos** [comment]
```java
package server.service.email;

import entities.EmailInteraction;
import repo.impl.EmailInteractionRepository;
import java.io.IOException;
import javax.mail.Message;
import javax.mail.MessagingException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 *
 * @author plourand
 */
@Service
public class EmailService {

	@Autowired
	private EmailInteractionRepository emailRepo;

	@Transactional
	public void saveEmail(Message mail) throws MessagingException, IOException {
		EmailInteraction interaction = new EmailInteraction();
		interaction.setFromAddress(mail.getFrom()[0].toString());
		interaction.setToAddress(mail.getAllRecipients()[0].toString());
		interaction.setSubject(mail.getSubject());
		
		emailRepo.save(interaction);
	}
}
```

```java
package server.service.email;

import com.icegreen.greenmail.spring.GreenMailBean;
import entities.EmailInteraction;
import repo.impl.EmailInteractionRepository;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import static org.mockito.Mockito.any;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

/**
 *
 * @author plourand
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = {"classpath*:spring/service-email.xml", "classpath*:spring/test-email.xml"})
public class EmailServiceTest {

	@Autowired
	private GreenMailBean mailBean;
	
	@Autowired
	private EmailInteractionRepository emailRepo;
	
	@Test
	public void successfulSave() throws InterruptedException {
		mailBean.sendEmail("philip@theblacklodge", "admin@theblacklodge", "subject", "content");

		Thread.sleep(200000);

		verify(emailRepo, times(1)).save(any(EmailInteraction.class));
	}
}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:int="http://www.springframework.org/schema/integration"
       xmlns:int-mail="http://www.springframework.org/schema/integration/mail"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util.xsd
                           http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
                           http://www.springframework.org/schema/integration/mail http://www.springframework.org/schema/integration/mail/spring-integration-mail.xsd
                           http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
                           http://www.springframework.org/schema/integration http://www.springframework.org/schema/integration/spring-integration.xsd">

    <context:property-placeholder location="classpath:config/mail.properties"/>

    <int-mail:inbound-channel-adapter id="emailAdapter"
                                      channel="incoming.mail.channel"
                                      auto-startup="true"
                                      should-delete-messages="true"
                                      should-mark-messages-as-read="true"
                                      store-uri="imap://admin:password@theblacklodge:3025/INBOX" >
        <int:poller max-messages-per-poll="40" fixed-rate="100" />
    </int-mail:inbound-channel-adapter>
    
    <int:channel id="incoming.mail.channel"/>

    <int:chain input-channel="incoming.mail.channel">
        <int:service-activator ref="emailService" method="saveEmail"/>
    </int:chain>

    <bean id="emailService" class="service.email.EmailService" />
</beans>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:mockito="http://www.mockito.org/spring/mockito"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
                           http://www.mockito.org/spring/mockito http://www.mockito.org/spring/mockito.xsd">

    <bean id="emailServer" class="com.icegreen.greenmail.spring.GreenMailBean">
        <property name="autostart" value="true"/>
        <property name="smtpProtocol" value="true" />
        <property name="pop3Protocol" value="true" />
        <property name="imapProtocol" value="true" />
        <property name="portOffset" value="3000" />
        <property name="hostname" value="theblacklodge" />
        <property name="users">
            <list>
                <value>philip:password@theblacklodge</value>
                <value>admin:password@theblacklodge</value>
            </list>
        </property>
    </bean>

    <mockito:mock id="emailRepo" class="repo.impl.EmailInteractionRepository" />
</beans>
```

**Comment by marcelmay** [comment]
Hi Philip,

thanks for the input. EmailInteractionRepository is missing but I can work around that.
Here are some comments:

1. You speak IMAP using the SMTP port **3025**, which should be **3143** instead when configuring int-mail:inbound-channel-adapter:
> "store-uri="imap://admin:password@theblacklodge:**3025**/INBOX"

2. Make sure "theblacklodge" is DNS resolvable (required by the way org.springframework.integration.mail.AbstractMailReceiver creates the JavaMail Store).
   Test this by using:
>   ping theblacklodge

3. There is a GreenMail issue with parentheses around IMAP Search Flags, for which I will open another issue once I got a simple test for reproduction running.

**Comment by philiplourandos** [comment]
> You speak IMAP using the SMTP port 3025, which should be 3143

*facepalm* yup that's the main culprit right there. 

> Make sure "theblacklodge" is DNS resolvable (required by the way 

Yup did have entry in /etc/hosts

> There is a GreenMail issue with parentheses around IMAP Search Flags

Think I am seeing the same thing now

```txt
07:57:35.987 [task-scheduler-4] DEBUG o.s.i.mail.ImapMailReceiver - This email server does not support RECENT or USER flags. System flag 'Flag.FLAGGED' will be used to prevent duplicates during email fetch.
07:57:35.987 [Thread-5] DEBUG c.i.g.imap.ImapRequestHandler - C: tag=A800, command=SEARCH
07:57:35.987 [Thread-5] DEBUG c.i.g.imap.commands.SearchCommand - Search request is 'NOT'
07:57:35.987 [Thread-5] DEBUG c.i.g.imap.commands.SearchCommand - Search request is '(ANSWERED)'
07:57:35.987 [Thread-5] WARN  c.i.g.imap.commands.SearchCommand - Ignoring not yet implemented search command '(ANSWERED)'
java.lang.IllegalArgumentException: No enum constant com.icegreen.greenmail.imap.commands.SearchKey.(ANSWERED)
	at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_51]
	at com.icegreen.greenmail.imap.commands.SearchKey.valueOf(SearchKey.java:92) ~[greenmail-1.4.1.jar:na]
	at com.icegreen.greenmail.imap.commands.SearchCommand$SearchCommandParser.searchTerm(SearchCommand.java:121) ~[greenmail-1.4.1.jar:na]
	at com.icegreen.greenmail.imap.commands.SearchCommand.doProcess(SearchCommand.java:51) [greenmail-1.4.1.jar:na]
	at com.icegreen.greenmail.imap.commands.SearchCommand.doProcess(SearchCommand.java:42) [greenmail-1.4.1.jar:na]
	at com.icegreen.greenmail.imap.commands.CommandTemplate.process(CommandTemplate.java:48) [greenmail-1.4.1.jar:na]
	at com.icegreen.greenmail.imap.ImapRequestHandler.doProcessRequest(ImapRequestHandler.java:98) [greenmail-1.4.1.jar:na]
	at com.icegreen.greenmail.imap.ImapRequestHandler.handleRequest(ImapRequestHandler.java:51) [greenmail-1.4.1.jar:na]
	at com.icegreen.greenmail.imap.ImapHandler.run(ImapHandler.java:94) [greenmail-1.4.1.jar:na]
	at com.icegreen.greenmail.server.AbstractServer$1.run(AbstractServer.java:103) [greenmail-1.4.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
```

**Comment by buildscientist** [comment]
@marcelmay Can I close this issue? Looks like it's been resolved with your commit in 1acb351f159f6a1428475bd04f8122177f610b89

**Comment by marcelmay** [comment]
@philiplourandos :
Just updated snapshots deployment to https://oss.sonatype.org/content/repositories/snapshots with version 1.4.2-SNAPSHOT. Please reopen if problem persists.
